# Generated by Django 2.2.18 on 2021-04-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='healthCard',
        ),
    ]
