# Generated by Django 2.2.18 on 2021-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_customuser_healthcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='healthCard',
            field=models.BooleanField(null=True),
        ),
    ]
