# Generated by Django 2.2.18 on 2021-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_customuser_healthcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='healthCardAccept',
            field=models.BooleanField(null=True),
        ),
    ]
