# Generated by Django 2.2.18 on 2021-04-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_customuser_healthcardaccept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='healthCardAccept',
            new_name='healthCardAcceptByAdmin',
        ),
    ]
