# Generated by Django 2.2.18 on 2021-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_healthcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=4492910025236038, editable=False, unique=True),
        ),
    ]
