# Generated by Django 2.2.18 on 2021-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20210410_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=4030669950514779, editable=False, unique=True),
        ),
    ]
