# Generated by Django 2.2.18 on 2021-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20210410_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=461425772843, editable=False, unique=True),
        ),
    ]
