# Generated by Django 2.2.18 on 2021-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20210410_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcNo', models.IntegerField()),
                ('date', models.DateField()),
                ('payment', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userImg',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=485405873126, editable=False, unique=True),
        ),
    ]
