# Generated by Django 2.2.18 on 2021-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20210416_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappoinment',
            name='id',
        ),
        migrations.AddField(
            model_name='bookappoinment',
            name='bookId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=470977315673, editable=False, unique=True),
        ),
    ]
