# Generated by Django 2.2.18 on 2021-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_auto_20210416_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappoinment',
            name='patientName',
            field=models.CharField(default='Gaurav Barot', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=459175790235, editable=False, unique=True),
        ),
    ]
