# Generated by Django 2.2.18 on 2021-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_auto_20210416_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappoinment',
            name='time',
            field=models.TimeField(default="00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=437452626653, editable=False, unique=True),
        ),
    ]
