# Generated by Django 2.2.18 on 2021-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_auto_20210416_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappoinment',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookappoinment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=481299910575, editable=False, unique=True),
        ),
    ]
