# Generated by Django 3.2 on 2021-04-24 17:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_auto_20210420_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientId', models.IntegerField()),
                ('patientName', models.CharField(max_length=500)),
                ('doctorId', models.IntegerField()),
                ('doctorName', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('hc', models.IntegerField()),
                ('itemName', jsonfield.fields.JSONField(default=dict)),
                ('itemBill', jsonfield.fields.JSONField(default=dict)),
                ('totalBill', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='patientId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=424603742941, editable=False, unique=True),
        ),
    ]
