# Generated by Django 3.2 on 2021-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_auto_20210424_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='appoId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=478186080409, editable=False, unique=True),
        ),
    ]
