# Generated by Django 3.2.5 on 2021-11-02 13:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_auto_20210501_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='itemBill',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='itemName',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=474088142049, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='days',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='qty',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='tblName',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='tblTime',
            field=jsonfield.fields.JSONField(),
        ),
    ]
