# Generated by Django 3.2.5 on 2021-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_auto_20211102_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='hcNo',
            field=models.IntegerField(default=414834806067, editable=False, unique=True),
        ),
    ]
