# Generated by Django 3.2.5 on 2021-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_auto_20211103_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='hc',
        ),
        migrations.RemoveField(
            model_name='bookappoinment',
            name='hcNo',
        ),
    ]
