# Generated by Django 3.2.5 on 2021-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_auto_20211103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
