# Generated by Django 3.2.5 on 2021-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_customuser_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
