# Generated by Django 3.2.5 on 2021-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_alter_customuser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createdByUser',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
